[build]
  publish = "."

# Normalize /adminpsc to index.html
[[redirects]]
  from = "/adminpsc"
  to = "/adminpsc/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/adminpsc/"
  to = "/adminpsc/index.html"
  status = 200
  force = true

# Pretty URLs for key pages
[[redirects]]
  from = "/adminpsc/login"
  to = "/adminpsc/login.html"
  status = 200
  force = true

[[redirects]]
  from = "/adminpsc/reset"
  to = "/adminpsc/reset.html"
  status = 200
  force = true

[[redirects]]
  from = "/adminpsc/home"
  to = "/adminpsc/landing.html"
  status = 200
  force = true

# Security & caching rules
[[headers]]
  for = "/adminpsc/*.html"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "SAMEORIGIN"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/adminpsc/*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/adminpsc/*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/adminpsc/*.{png,webp,svg,woff2}"
  [headers.values]
    Cache-Control = "public, max-age=604800"